// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type CompanyStatus struct {
	SecNo        string `json:"sec_no"`
	CompanyName  string `json:"company_name"`
	DateApproved string `json:"date_approved"`
	Licenses     string `json:"licenses"`
	Status       string `json:"status"`
}
